name: simag_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  file_picker: ^8.0.0+1
  cupertino_icons: 1.0.2
  get: 4.6.6
  lottie: 3.1.0
  page_transition: 2.1.0
  flutter_native_splash: 2.3.11
  flutter_form_builder: 9.2.1
  zoom_tap_animation: 1.1.0
  pin_code_fields: 8.0.1
  google_fonts: 6.1.0
  url_launcher: 6.2.6
  google_maps_flutter: 2.2.8
  intl: 0.18.1
  form_builder_validators: 9.1.0
  http: 1.2.1
  provider: 6.1.2
  shared_preferences: 2.2.3
  flutter: 
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/lottie/
    - assets/logo/
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
  uses-material-design: true
